<a href="https://colab.research.google.com/github/siddhanthnagrath1/Earthquake-Prediction/blob/main/Earthquake_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
import time
from datetime import datetime

In [2]:
df1=pd.read_csv("database (1).csv")

In [5]:
from datetime import datetime

epoch = datetime(1970, 1, 1)

def mapdateTotime(x):
    try:
        dt = datetime.strptime(x, "%m/%d/%Y")
    except ValueError:
        dt = datetime.strptime(x, "%Y-%m-%dT%H:%M:%S.%fZ")
    diff = dt - epoch
    return diff.total_seconds()

df1['Date'] = df1['Date'].apply(mapdateTotime)


In [7]:

col1 = df1[['Date', 'Latitude', 'Longitude', 'Depth']]
col2 = df1['Magnitude']


InputX1 = col1.values
InputY1 = col2.values
print(InputX1)


[[-1.5768000e+08  1.9246000e+01  1.4561600e+02  1.3160000e+02]
 [-1.5750720e+08  1.8630000e+00  1.2735200e+02  8.0000000e+01]
 [-1.5742080e+08 -2.0579000e+01 -1.7397200e+02  2.0000000e+01]
 ...
 [ 1.4828832e+09  3.6917900e+01  1.4042620e+02  1.0000000e+01]
 [ 1.4829696e+09 -9.0283000e+00  1.1866390e+02  7.9000000e+01]
 [ 1.4830560e+09  3.7397300e+01  1.4141030e+02  1.1940000e+01]]


In [8]:
X1_min = np.amin(InputX1,0)
X1_max = np.amax(InputX1,0)
print("Mininum values:",X1_min)
print("Maximum values:",X1_max)
Y1_min = np.amin(InputY1)
Y1_max = np.amax(InputY1)
InputX1_norm = (InputX1-X1_min)/(X1_max-X1_min)
InputY1_norm = InputY1  #No normalization in output

#Reshape
Xfeatures = 3 #Number of input features
Yfeatures = 1 #Number of input features
samples = 23000 # Number of samples

InputX1_reshape = np.resize(InputX1_norm,(samples,Xfeatures))
InputY1_reshape = np.resize(InputY1_norm,(samples,Yfeatures))

Mininum values: [-1.57680e+08 -7.70800e+01 -1.79997e+02 -1.10000e+00]
Maximum values: [1.483056e+09 8.600500e+01 1.799980e+02 7.000000e+02]


In [9]:
#Training data
batch_size = 2000
InputX1train = InputX1_reshape[0:batch_size,:]
InputY1train = InputY1_reshape[0:batch_size,:]
#Validation data
v_size = 2500
InputX1v = InputX1_reshape[batch_size:batch_size+v_size,:]
InputY1v = InputY1_reshape[batch_size:batch_size+v_size,:]

In [10]:
learning_rate = 0.001
training_iterations = 1000
display_iterations = 200

In [15]:
import tensorflow as tf

# Assuming Xfeatures is defined somewhere in your code
Xfeatures = 10

# Input
X = tf.keras.layers.Input(shape=(Xfeatures,), dtype=tf.float32)

# Output
Y = tf.keras.layers.Input(shape=(1,), dtype=tf.float32)

# Example usage in a model
hidden = tf.keras.layers.Dense(64, activation='relu')(X)
output = tf.keras.layers.Dense(1, activation='sigmoid')(hidden)

model = tf.keras.models.Model(inputs=X, outputs=output)

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Example usage: fit the model with some data
# model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_val, y_val))


In [17]:


# Define the number of neurons in each layer
Xfeatures = 10
L1 = 3
L2 = 3
L3 = 3
Yfeatures = 1

# Layer 1 weights
W_fc1 = tf.Variable(tf.random.uniform([Xfeatures, L1]))
b_fc1 = tf.Variable(tf.constant(0.1, shape=[L1]))

# Layer 2 weights
W_fc2 = tf.Variable(tf.random.uniform([L1, L2]))
b_fc2 = tf.Variable(tf.constant(0.1, shape=[L2]))

# Layer 3 weights
W_fc3 = tf.Variable(tf.random.uniform([L2, L3]))
b_fc3 = tf.Variable(tf.constant(0.1, shape=[L3]))

# Output layer weights
W_fO = tf.Variable(tf.random.uniform([L3, Yfeatures]))
b_fO = tf.Variable(tf.constant(0.1, shape=[Yfeatures]))


In [18]:
#Layer 1
matmul_fc1=tf.matmul(X, W_fc1) + b_fc1
h_fc1 = tf.nn.relu(matmul_fc1)   #ReLU activation
#Layer 2
matmul_fc2=tf.matmul(h_fc1, W_fc2) + b_fc2
h_fc2 = tf.nn.relu(matmul_fc2)   #ReLU activation
#Layer 3
matmul_fc3=tf.matmul(h_fc2, W_fc3) + b_fc3
h_fc3 = tf.nn.relu(matmul_fc3)   #ReLU activation
#Output layer
matmul_fc4=tf.matmul(h_fc3, W_fO) + b_fO
output_layer = matmul_fc4  #linear activation

In [21]:
import tensorflow as tf

# Assuming Xfeatures and Yfeatures are defined somewhere in your code
Xfeatures = 10
Yfeatures = 1

# Example network architecture using Functional API
inputs = tf.keras.Input(shape=(Xfeatures,), dtype=tf.float32)
hidden = tf.keras.layers.Dense(10, activation='relu')(inputs)
output_layer = tf.keras.layers.Dense(Yfeatures, activation=None)(hidden)

# Define the model
model = tf.keras.Model(inputs=inputs, outputs=output_layer)

# Compile the model
model.compile(optimizer='adam',
              loss='mean_squared_error',
              metrics=['mse'])

# Example usage: creating dummy data for demonstration
import numpy as np
X_train = np.random.randn(100, Xfeatures)
Y_train = np.random.randn(100, Yfeatures)

# Fit the model
model.fit(X_train, Y_train, epochs=10, batch_size=32)


Epoch 1/10
4/4 [==============================] - 1s 6ms/step - loss: 1.7219 - mse: 1.7219
Epoch 2/10
4/4 [==============================] - 0s 4ms/step - loss: 1.6756 - mse: 1.6756
Epoch 3/10
4/4 [==============================] - 0s 4ms/step - loss: 1.6431 - mse: 1.6431
Epoch 4/10
4/4 [==============================] - 0s 5ms/step - loss: 1.6102 - mse: 1.6102
Epoch 5/10
4/4 [==============================] - 0s 4ms/step - loss: 1.5821 - mse: 1.5821
Epoch 6/10
4/4 [==============================] - 0s 4ms/step - loss: 1.5521 - mse: 1.5521
Epoch 7/10
4/4 [==============================] - 0s 5ms/step - loss: 1.5271 - mse: 1.5271
Epoch 8/10
4/4 [==============================] - 0s 4ms/step - loss: 1.5012 - mse: 1.5012
Epoch 9/10
4/4 [==============================] - 0s 4ms/step - loss: 1.4747 - mse: 1.4747
Epoch 10/10
4/4 [==============================] - 0s 4ms/step - loss: 1.4499 - mse: 1.4499


In [23]:
import tensorflow as tf
import numpy as np

# Assuming InputX1train, InputY1train, InputX1v, InputY1v are defined somewhere in your code
InputX1train = np.random.randn(100, Xfeatures)  # Example data
InputY1train = np.random.randn(100, Yfeatures)  # Example data
InputX1v = np.random.randn(50, Xfeatures)  # Example validation data
InputY1v = np.random.randn(50, Yfeatures)  # Example validation data

# Define your model architecture and compile it
inputs = tf.keras.Input(shape=(Xfeatures,))
hidden = tf.keras.layers.Dense(10, activation='relu')(inputs)
output_layer = tf.keras.layers.Dense(Yfeatures, activation=None)(hidden)

model = tf.keras.Model(inputs=inputs, outputs=output_layer)
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
history = model.fit(InputX1train, InputY1train, epochs=10, validation_data=(InputX1v, InputY1v))

# Save the model
model.save("/tmp/earthquake_model.h5")

# Evaluate the model on training and validation data
train_loss = model.evaluate(InputX1train, InputY1train)
val_loss = model.evaluate(InputX1v, InputY1v)

print("Final training loss:", train_loss)
print("Final validation loss:", val_loss)


Epoch 1/10
4/4 [==============================] - 1s 74ms/step - loss: 1.4748 - val_loss: 1.1945
Epoch 2/10
4/4 [==============================] - 0s 17ms/step - loss: 1.4435 - val_loss: 1.1879
Epoch 3/10
4/4 [==============================] - 0s 18ms/step - loss: 1.4185 - val_loss: 1.1809
Epoch 4/10
4/4 [==============================] - 0s 15ms/step - loss: 1.3981 - val_loss: 1.1741
Epoch 5/10
4/4 [==============================] - 0s 21ms/step - loss: 1.3802 - val_loss: 1.1672
Epoch 6/10
4/4 [==============================] - 0s 13ms/step - loss: 1.3640 - val_loss: 1.1615
Epoch 7/10
4/4 [==============================] - 0s 19ms/step - loss: 1.3457 - val_loss: 1.1561
Epoch 8/10
4/4 [==============================] - 0s 18ms/step - loss: 1.3305 - val_loss: 1.1495
Epoch 9/10
4/4 [==============================] - 0s 19ms/step - loss: 1.3118 - val_loss: 1.1430
Epoch 10/10
4/4 [==============================] - 0s 4ms/step - loss: 1.2846


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


2/2 [==============================] - 0s 10ms/step - loss: 1.1374
Final training loss: 1.2846214771270752
Final validation loss: 1.1374173164367676


In [32]:
# Assuming you have defined and compiled your model previously
model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(10,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='linear'))  # Adjust activation and units as per your problem

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mse'])

# Train the model
history = model.fit(InputX1train, InputY1train, batch_size=10, epochs=20, verbose=1, validation_data=(InputX1v, InputY1v))


Epoch 1/20
10/10 [==============================] - 1s 23ms/step - loss: 1.4642 - mse: 1.4642 - val_loss: 1.3899 - val_mse: 1.3899
Epoch 2/20
10/10 [==============================] - 0s 7ms/step - loss: 1.2852 - mse: 1.2852 - val_loss: 1.2489 - val_mse: 1.2489
Epoch 3/20
10/10 [==============================] - 0s 7ms/step - loss: 1.1697 - mse: 1.1697 - val_loss: 1.1573 - val_mse: 1.1573
Epoch 4/20
10/10 [==============================] - 0s 7ms/step - loss: 1.0941 - mse: 1.0941 - val_loss: 1.0958 - val_mse: 1.0958
Epoch 5/20
10/10 [==============================] - 0s 7ms/step - loss: 1.0479 - mse: 1.0479 - val_loss: 1.0564 - val_mse: 1.0564
Epoch 6/20
10/10 [==============================] - 0s 7ms/step - loss: 1.0215 - mse: 1.0215 - val_loss: 1.0314 - val_mse: 1.0314
Epoch 7/20
10/10 [==============================] - 0s 11ms/step - loss: 0.9982 - mse: 0.9982 - val_loss: 1.0190 - val_mse: 1.0190
Epoch 8/20
10/10 [==============================] - 0s 11ms/step - loss: 0.9841 - mse: 0

In [33]:
[test_loss, test_acc] = model.evaluate(InputX1v, InputY1v)

# Print evaluation results
print("Evaluation result on Test Data : Loss = {}, accuracy = {}".format(test_loss, test_acc))

2/2 [==============================] - 0s 9ms/step - loss: 0.9780 - mse: 0.9780
Evaluation result on Test Data : Loss = 0.9779589176177979, accuracy = 0.9779589176177979
